name: Publish
on:
  release:
    types: [released]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: "**/pyproject.toml"
    - name: Install Uqbar
      run: pip install -e .[docs]
    - uses: kamiazya/setup-graphviz@v1
    - name: Build docs
      run: make docs
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ./docs/build/html/

  build-dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build sdist
      run: pipx run build --sdist
    - name: Build universal wheel
      run: pipx run build --wheel
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.tar.gz

  upload-to-pypi:
    name: Publish release to PyPI
    needs: [build-docs, build-dist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  update-gh-pages:
    name: Update gh-pages
    needs: [upload-to-pypi]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: docs
        path: docs
    - name: Clone gh-pages
      run: git clone --branch gh-pages `git config --get remote.origin.url` gh-pages/
    - name: Rsync docs
      run: rsync -rtv --del --exclude=.git docs/ gh-pages/
    - name: Touch .nojekyll
      run: touch gh-pages/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        allow_empty_commit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
